spring:
  ai:
    openai:
      ## OpenAPI 地址
      base-url: https://api.deepseek.com
      ## OpenAPI API Key
      api-key: sk-8e246d7869ad41fab44f5c553bd1edfb
      chat:
        options:
          ## OpenAPI 模型
          model: deepseek-chat
          temperature: 0.7